config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile/index'
  root to: "profile#index"
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'posts/index'

root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titile, :body, :picture)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    require "requests"

response = Requests.request("GET", "https://www.googleapis.com/books/v1/volumes?q=ruby+on+rails")

# Now you have these methods available

response.body    #=> String with the response body
@data = JSON.parse(response.body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.text_field :post_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_header.html.erb
<div class="container-fluid">

<header class="main_h">

    <div class="row">
        <a class="logo" href="#">HOME</a>

        <div class="mobile-toggle">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <nav>
            <ul>
                <li><a href=".sec01">Section 01</a></li>
                <li><a href=".sec02">Section 02</a></li>
                <li><a href=".sec03">Section 03</a></li>
                <li><a href=".sec04">Section 04</a></li>
            </ul>
        </nav>

    </div> <!-- / row -->

</header>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Myblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="container-fluid">
  <%= render :partial => 'layouts/header'%>

<% if user_signed_in? %>
<div>
  <%= current_user.email %>
</div>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
<% else %>
  <%= link_to "Log in", user_session_path %>
<% end %>



  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
</div>

  </body>
</html>

app/views/partials/_api.html.erb
<div class="jumbotron">
<% @data['items'].each do |book| %>
<%= image_tag book['volumeInfo']['imageLinks']['smallThumbnail'] %>

<% end %>
</div>

app/views/partials/_banner.html.erb
<div class="hero">
    <div class="row">
    <div class="col-md-6">
<h1><span>this is ...!</span><br>place holder</h1>
    </div>
    <div id="animtype" class="col-md-6">
      <h1 class="cd-headline letters type">
        <span class="text-left">this is animation</span>
        <br>
        <span class="cd-words-wrapper waiting">
          <b class="is-visible">Web Developer</b>
          <b>Tech fanatic</b>
          <b>Technopreneur</b>
          <b>African...</b>
        </span>
      </h1>
    </div>

    </div>



    <div class="mouse">
        <span></span>
    </div>

</div>

app/views/partials/_career.html.erb
<section id="career" class="content-block content-1-2">
  <div class="container">
    <!-- Start Row -->
    <div class="row">
      <div class="col-sm-6">
        <h2>Career and Education</h2>
        <p class="lead">Currently...</p>
        <p>
          Telematics Consultant - ENAiKOON GmbH <br>
          Digital Marketing & Web Dev - ginstr GmbH <br>
          Information Management and Information Technology - Humboldt University - Berlin
         </p>
        <div class="row">
          <div class="col-sm-5 col-xs-12">
            <a href="#" class="btn btn-block btn-primary">
              <span class="fa fa-cloud-upload"></span>
              Lebenslauf</a>
          </div>
          <div class="col-sm-5 col-xs-12">
            <a href="#" class="btn btn-block btn-warning">
              <span class="fa fa-check"></span>
              CV </a>
          </div>
        </div>
      </div>
      <div class="col-sm-5 col-sm-offset-1">
        <img class="img-rounded img-responsive" src="assets/dummy-1134x756-Rope.jpg">
      </div>
    </div>
    <!--// END Row -->
  </div>
</section>

app/views/partials/_clickable.html.erb
<section id="content-3-10" class="content-block-nopad content-3-10 bg-asbestos-hover">
  <div class="image-container col-sm-6 col-xs-12 pull-left">
    <div class="background-image-holder"></div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-6 col-xs-12 content">
        <h3>Still nothing to write</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
        <a href="#" class="btn btn-outline btn-outline outline-dark">clickable</a>
      </div>
    </div>
    <!-- /.row-->
  </div>
  <!-- /.container -->
</section>

app/views/partials/_expression.html.erb
<section id="content-1-1" class="content-block content-1-1 min-height-600px bg-black-hover">
  <div class="container text-center">
    <h1>Freedom of expression</h1>
    <div class="col-sm-8 col-sm-offset-2">
      <p class="lead">Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque quiae sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent.</p>
    </div>
  </div>
</section>

app/views/partials/_link.html.erb
<section id="content-2-10" class="content-2-10 content-block">
  <div class="container bg-white border-box">
    <div class="col-md-8 col-xs-12 pull-left">
      <h2>to some random site</h2>
    </div>
    <div class="col-md-3 col-xs-12 pull-right">
      <a href="#" class="btn btn-lg btn-info btn-block">More Info</a>
    </div>
  </div>
</section>

app/views/partials/_philosophy.html.erb
<section id="philosophy" class="content-block content-1-2">
<div class="row">
  <div class="col-md-5 col-md-offset-1 col-sm-12">
    <img class="img-responsive" src="assets/Menu.jpg">
  </div>

  <div class="col-md-5 col-sm-12">
    <h3>Philosophy</h3>
    <i class="fa fa-quote-left fa-3x fa-pull-left fa-border" aria-hidden="true"></i> ...I pride myself on my ability to recognize and articulate a distinct voice for every project. I am driven by the in-depth problem solving that coding provides, new challenges, and the opportunity to learn from my peers. I am looking for a company that values these ideals. I want to work alongside dedicated groups of problem solvers who are passionate about the company’s mission.

    <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
<span class="sr-only">Loading...</span>
    </p>
  </div>
</div>
</section>

app/views/partials/_projects.html.erb
<section id="content-1-6" class="content-1-6 content-block">
  <div class="container">
    <div class="row text-center">
      <h2>My current projects</h2>
    </div>
    <!--end of row-->
    <div class="row client-row">
      <div class="row-wrapper">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <img alt="client" src="images/partner-logos/logo-less.png">
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <img alt="client" src="images/partner-logos/logo-less.png">
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <img alt="client" src="images/partner-logos/logo-sass.png">
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <img alt="client" src="images/partner-logos/logo-jquery.png">
        </div>
      </div>
    </div>
    <!-- /.row -->

    <!-- Only delete this to enable second row

    <div class="row client-row">
      <div class="row-wrapper">
        <div class="col-md-3 hidden-sm hidden-xs">
          <img alt="client" src="images/partner-logos/logo-grunt.png">
        </div>
        <div class="col-md-3 hidden-sm hidden-xs">
          <img alt="client" src="images/partner-logos/logo-bower.png">
        </div>
        <div class="col-md-3 hidden-sm hidden-xs">
          <img alt="client" src="images/partner-logos/logo-yeoman.png">
        </div>
        <div class="col-md-3 hidden-sm hidden-xs">
          <img alt="client" src="images/partner-logos/logo-angularjs.png">
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

app/views/posts/_altpost.html.erb
<div class="blog-card alt">
	<div class="photo"><%= image_tag post.picture, :class => "img-responsive"%></div>
	<ul class="details">
		<li class="author"><a href="#">Victor</a></li>
		<li class="date">Aug. 28, 2016</li>
		<li class="tags">
			<ul>
				<li><a href="#">Learn</a></li>
				<li><a href="#">Code</a></li>
				<li><a href="#">HTML</a></li>
				<li><a href="#">CSS</a></li>
			</ul>
		</li>
	</ul>
	<div class="description">
		<h1><%=  link_to post.titile, post %></h1>
		<h2></h2>
		<%=post.body.truncate(150, separator: ' ', omission:' ')%>
    <%= link_to '...more', post %>


    <%= link_to 'Edit', edit_post_path(post), :class=>"btn btn-success"%>
    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?'}, :class=>"btn btn-danger" %>
	</div>
</div>

app/views/posts/_form.html.erb
<div class="container">

<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<form>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :titile, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", id: "editor" %>
  </div>



<div class="field">
  <%= f.label :picture %>
  <%= f.file_field :picture %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <script>
        $(function() {
            $('#editor').froalaEditor()
        });
    </script>

</form>



<% end %>

</div>

app/views/posts/_post.html.erb
<%
=begin %>
partials. Instead of a loop for (in this case post), create a file naming it as _filename-html.erb

<%= render partial: @posts %>
on index.html.erb will be the call
<%
=end %>
<!--


<div id="newcolor" class="col-xs-6 colborder" >
    <h1 class="text-right"><%=  link_to post.titile, post %></h1>
    <hr>

<%= image_tag post.picture, :class => "img-responsive img-circle"%>

    <p class="text-left">
        <%=post.body.truncate(150, separator: ' ', omission:' ...')%>
        <%= link_to 'more', post %></p>
    <%= link_to 'Edit', edit_post_path(post), :class=>"btn btn-success"%>
    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?'}, :class=>"btn btn-danger" %>
</div>  -->





<!--PEN CODE-->
<div class="blog-card">
	<div class="photo"><%= image_tag post.picture, :class => "img-responsive"%></div>
	<ul class="details">
		<li class="author"><a href="#">Victor</a></li>
		<li class="date">Aug. 28, 2016</li>
		<li class="tags">
			<ul>
				<li><a href="#">Learn</a></li>
				<li><a href="#">Code</a></li>
				<li><a href="#">HTML</a></li>
				<li><a href="#">CSS</a></li>
			</ul>
		</li>
	</ul>
	<div class="description">
		<h1><%=  link_to post.titile, post %></h1>
		<h2></h2>
		<%=post.body.truncate(150, separator: ' ', omission:' ')%>
    <%= link_to '...more', post %><br><br>

		<% if user_signed_in? %>
    <%= link_to 'Edit', edit_post_path(post), :class=>"btn btn-success"%>
		<br><br>
    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?'}, :class=>"btn btn-danger" %>
		<% end %>
	</div>
</div>
<!--END PEN CODE-->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container ">




    <p id="notice"><%= notice %></p>




    <h1>Posts</h1>

    <br>

    <%= link_to 'New Post', new_post_path %>

    <div class="bord1" >
        <%= render partial: @posts %>
    </div>



</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container">
  <div id="pagetitle" class="right-align">
    <h2>
    <u>Channels</u>
    </h2>
  </div>
  <h1><%= @post.titile.upcase %></h1>
  <%= image_tag @post.picture, :class => "img-responsive img-circle" %>
  <%=@post.body %>
  <%= link_to 'Edit', edit_post_path(@post), :class => "btn btn-success" %>
  <%= link_to 'Back', posts_path, :class =>"btn btn-success" %>
</div>